### ISSUE TITLE
'PayloadString' object has no attribute 'get'

### ISSUE THREAD

**Issue by ewjoachim** [peopledoc/jenkins-epo#290]
Some (most ?) jobs seems not to be able to process Jenkins payload after an upgrade from 2.52 to 2.59.

An error is displayed in the logs : 'PayloadString' object has no attribute 'get'

Will try to run with verbose/debug to pinpoint the issue.
